name: Build and Update MinSDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Update MinSDK in AndroidManifest.xml
      run: |
        sed -i 's/android:minSdkVersion="[0-9]*"/android:minSdkVersion="21"/g' app/src/main/AndroidManifest.xml || true
        sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/g' app/build.gradle || true

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
